name: rc_learn 
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - jupyter
  - pandas
  - xlrd
  - numpy
  - seaborn
  - matplotlib
  - notebook
  - scikit-learn
  - scipy
  - pyemma
  - sphinx
  - openmmtools
